# BucikGenerators
# Author: workonfire aka Buty935
# Contact: workonfire (Discord)

options:
  auto-save-interval: 18000 # in ticks. 1 second = 20 ticks. Currently set to 15 minutes
  locale: en
  play-sounds: true
  show-particles: true
  debug: false # Enable this to allow displaying full error messages.
