name: BucikGenerators
version: 1.1.5
description: A customizable plugin for setting up block generators.
main: pl.workonfire.bucik.generators.BucikGenerators
api-version: 1.13
softdepend: [Vault]
authors: [Buty935]
commands:
  generators:
    description: "Main command."
    aliases: [gene, generator]
  drop:
    description: "A command for displaying generator drop details."
    aliases: [genedrop, generatordrop]
